### PR TITLE
Chore: abstract email service

### PR DESCRIPTION
**Pull request by AH-dark**
When browsing the codes, I found that the email service you use is not abstracted, but the adapted SMTP and Alibaba Cloud DM listed as two different functions.
Obviously, when you want to improve the adaptability and expand this Service in the future, such a design will greatly improve the standardization and difficulty of adaptation.

So I submitted this Pull Request that abstracts it.

In addition, I noticed that the `AddToQueue(email Email)` function in `lib/email/queue.go` uses goroutine to pass email to the channel. 
This is meaningless, such a simple operation does not need to be asynchronous to reduce the duration, and may even be slowed down by coroutines.

Moreover, adding a pointer to the channel variable `emailCh` is completely meaningless.

If you think there is an error in my opinion, please point it out!

### CODE REVIEW

**Comment by AH-dark** [comment]
The reason why I submitted this pr was that I needed to add an adaptation of Mailgun to suit my needs, but it was barely abstracted. 

In this case, too much compatibility will cause its code to be messy, and for its follow-up and maintainability, I think it is my responsibility to abstract it first.

**Comment by qwqcode** [comment]
LGTM! Thanks so much for doing this!

**Comment by qwqcode** [comment]
但是对于你的观点 “adding a pointer to the channel variable `emailCh` is completely meaningless.” 这一点我并不认同，定义一个指针类型的 `emailCh` 变量作用是在当 `InitQueue` 函数没有被调用的时候，不会去 make 这个 `chan Email`，不占用计算机资源，这里的设计思路是 as lazy as possible

**Comment by AH-dark** [comment]
> 但是对于你的观点 “adding a pointer to the channel variable `emailCh` is completely meaningless.” 这一点我并不认同，定义一个指针类型的 `emailCh` 变量作用是在当 `InitQueue` 函数没有被调用的时候，不会去 make 这个 `chan Email`，不占用计算机资源，这里的设计思路是 as lazy as possible

but this channel is just an extremely small variable, and the chan type supports setting to `nil`, so it doesn't take up memory in this case?

also, how can you possibly not use email service? Since initialization must be performed, it is not necessary, is it?

**Pull request merged**
